### ISSUE TITLE
Pickle support (or another way to write to file?)

### ISSUE THREAD

**Issue by kholland950** [tburmeister/pyneural#3] opened 2016-03-19 19:46 UTC
@tburmeister , are you expecting to add pickle support? Or is there another way to write a network to a file? I would like to be able to load a network at the start of a program without training every time.

**Comment by tburmeister** [comment] 2016-03-19 20:11
You can use the `get_params` and `set_params`, together with numpy pickle support, to save and load networks, but I realize that's kind of a pain. I'll try to add `save` and `load` methods.

**Comment by kholland950** [comment] 2016-03-19 20:13
I tried that and upon activating the loaded network, Python terminated with: "'python' terminated by signal SIGFPE (Floating point exception)". Have you experienced that?

**Comment by tburmeister** [comment] 2016-03-19 20:15
Ouch. I have not run into that. Could you possibly post your code so I can try to reproduce?

**Comment by kholland950** [comment] 2016-03-19 20:20
That'd be kind of hard to do right now. Multiple files involved and I haven't published to github yet. I think I should be able to figure it out. So I should be able to save the network using the array from get_params and load the network using set_params? That's enough for me if that works.

Also, another question: On Linux, is openBLAS the only BLAS library you support? I can use openBLAS if necessary but I was just curious.

**Comment by kholland950** [comment] 2016-03-19 20:30
This is how I am attempting to write and load networks. Is there anymore initialization I have to do that I am missing in the load function?

``` python
def loadNet(fname):
    f = open(fname, "rb")
    data = pickle.load(f)
    params = data['params']
    net = pyneural.NeuralNet([784, 100, 10])
    net.set_params(params)
    return net

def writeNet(fname, net):
    f = open(fname, "wb")
    data = {}
    data['params'] = net.get_params()
    pickle.dump(data, f)
```

**Comment by tburmeister** [comment] 2016-03-19 21:07
That code works for me. What OS are you on?

openBLAS is the only BLAS library I've attempted to implement on Linux - others probably could work.

**Comment by kholland950** [comment] 2016-03-19 21:15
I'm on OS X. No luck yet.

I successfully setup on my Linux box! Took a while but it works!

**Comment by kholland950** [comment] 2016-03-19 21:20
It was a divide by zero issue, but am looking through your code and can't find a place where that would happen. It happens during activation of the network, and I saw division taking place in the sigmoid function of feed forward but that would never cause a divide by zero error... Hm. I'm activating the network using the same exact code both times so it has to be something with how I'm getting and settings params... But if that code above works for you then I'm at a loss.

**Comment by kholland950** [comment] 2016-03-19 23:43
I think I figured it out! batch_size is used in the neural_predict_prob in the neural.c file. If you instantiate a network and set_params, batch_size is never set. Maybe this is where the divide by zero error is happening?

**Comment by tburmeister** [comment] 2016-03-19 23:43
Haha I was just going comment that I think I had solved the problem. You are exactly right. I just pushed a fix - should work now.

**Comment by tburmeister** [comment] 2016-03-19 23:45
Also, changed the setup.py - try doing `pip install . --upgrade` from the pyneural directory.

This doesn't solve your initial problem - having an easy way to save and load networks - still planning to take a crack at that, but I think I'm done for tonight.

**Comment by kholland950** [comment] 2016-03-19 23:47
Thanks so much! Should update work the same as installing?

**Comment by kholland950** [comment] 2016-03-19 23:57
It worked! I can now read from file and write to file! Thank you so much.

BTW, thank you so much for the library. I was using PyBrain for weeks and was much to slow and doesn't support mini batching. This has saved my senior project, and also a ton of time so thank you! I really love it.

**Comment by tburmeister** [comment] 2016-03-21 01:21
Glad to hear you've found the library useful! I just pushed a commit that has new `load`, `loads`, `dump`, and `dumps` methods to make loading and saving networks easier. Going to close out this issue.

**Closed as completed by tburmeister** 2016-03-21 01:21 UTC
